Redo archive mechanism

diff --git a/bin/archive-branches b/bin/archive-branches
--- a/bin/archive-branches
+++ b/bin/archive-branches
@@ -1,8 +1,35 @@
-#!/bin/sh
+#!/usr/bin/perl
 
-TIME="`date +'%Y%m%d-%H%M%S'`"
+$| = 1;
 
-for f in "$@"
-do
-    git branch -m "$f" 000-archive--"$TIME"--"$f"
-done
+use strict;
+use warnings;
+
+use Cwd ('abs_path');
+use File::Basename;
+use POSIX ('strftime');
+
+my $root = abs_path();
+
+while(1)
+{
+    if(-d "$root/.git")
+    {
+        last;
+    }
+    if($root eq "/")
+    {
+        die "Cannot findup .git for repo root";
+    }
+    $root = dirname($root);
+}
+
+my $time = strftime('%Y%m%d-%H%M%S', localtime(time()));
+
+my @push = ("git", "push", "$root/.git/archive-repo", (map { "$_:$time--$_" } @ARGV));
+print "Running: (" . join(" ", map { "'$_'" } @push) . ")...\n";
+(system(@push) == 0) || die "Could not push: $!";
+
+my @del = ("git", "branch", "-D", @ARGV);
+print "Running: (" . join(" ", map { "'$_'" } @del) . ")...\n";
+(system(@del) == 0) || die "Could not delete: $!";
